#!/usr/bin/python

import imaplib
obj = imaplib.IMAP4('msx.tu-dresden.de',143)
obj.starttls()
obj.login('user','pass') # write your email and password
obj.select()
print(len(obj.search(None, 'UnSeen')[1][0].split()))
